name: unleashing_grpc
description: "A Flutter package showing how to utilize gRPC to implement machine control between multiple applications."
version: 0.0.1
homepage: https://github.com/lapumb-spindance/unleashing-grpc
issue_tracker: https://github.com/lapumb-spindance/unleashing-grpc/issues
publish_to: 'none'

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  grpc: ^4.0.0
  logging: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
